name: CI
on:
  pull_request:
  push:
    branches: [ main, master ]
permissions:
  contents: read
jobs:
  powershell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PSScriptAnalyzer
        run: |
          pwsh -NoLogo -Command "Install-Module PSScriptAnalyzer -Force -Scope CurrentUser"
      - name: Lint PowerShell scripts
        run: |
          pwsh -NoLogo -Command "Invoke-ScriptAnalyzer -Path . -Recurse -Severity Warning -Recurse"
      - name: Validate PowerShell syntax
        run: |
          pwsh -NoLogo -Command "Get-ChildItem -Path . -Filter '*.ps1' -Recurse | ForEach-Object { try { $null = [System.Management.Automation.Language.Parser]::ParseFile($_.FullName, [ref]$null, [ref]$null); Write-Host \"✓ $($_.Name) syntax valid\" } catch { Write-Error \"✗ $($_.Name) syntax error: $_\"; exit 1 } }"