name: CI
on:
  pull_request:
  push:
    branches: [ main ]
permissions:
  contents: read
jobs:
  powershell:
    if: ${{ hashFiles('**/*.ps1') != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PSScriptAnalyzer
        run: pwsh -NoLogo -Command "Install-Module PSScriptAnalyzer -Force; Invoke-ScriptAnalyzer -Path . -Recurse -Severity Warning" || true