name: Weekly Council Digest
on:
  schedule:
    - cron: "0 8 * * 1"
  workflow_dispatch:

jobs:
  digest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build digest (simple)
        id: digest
        run: |
          echo "Commit summary (last 7 days):" > digest.txt
          git log --since="7 days ago" --pretty="format:* %h %s" >> digest.txt
          echo "DIGEST<<EOF" >> $GITHUB_OUTPUT
          cat digest.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Post to Council
        env:
          DISCORD_WEBHOOK_COUNCIL: ${{ secrets.DISCORD_WEBHOOK_COUNCIL }}
        run: |
          jq -Rs '{content: .}' <<< "${{ steps.digest.outputs.DIGEST }}" \
            | curl -sS -X POST "$DISCORD_WEBHOOK_COUNCIL" \
                -H "content-type: application/json" \
                -d @-
